<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Article;
use App\Models\Video;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Buat 20 artikel dummy
        for ($i = 1; $i <= 20; $i++) {
            Article::create([
                'title' => 'Sample Article Title ' . $i,
                'content' => 'This is the full content for sample article number ' . $i . '. It is generated by a seeder.',
            ]);
        }

        // Buat 20 video dummy
        for ($i = 1; $i <= 20; $i++) {
            Video::create([
                'title' => 'Sample Video Title ' . $i,
                'video_url' => 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', // Placeholder URL
                'description' => 'Description for video number ' . $i,
            ]);
        }
    }
}
